version: "3.3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./log:/app/log
    environment:
      - NODE_ENV=production
      - MONGO_HOST=mongo
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
      - MAIL_SMTP_HOST=mail.server.net
      - MAIL_SMTP_PORT=smtpport
      - MAIL_SMTP_USERNAME=smtpusername
      - MAIL_SMTP_PASSWORD='smtppass'
      - MAIL_SENDER_ADDRESS=mail@example.com
      - API_URL=https://api_url
      - API_PORT=3000 # ignoring when NODE_ENV=production
      - APP_URL=https://app_url
      - APP_PORT=4200 # ignoring when NODE_ENV=production
    links:
      - mongo
  mongo:
    image: mongo:4.2
    volumes:
      - ./db:/data/db
      - ./init-mongo-user.js:/docker-entrypoint-initdb.d/init-mongo-user.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=origami
    ports:
      - 27017:27017
